#!/bin/sh -ex

DB_NAME=openphoto
DB_USER=openphoto
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/openphoto

# unpack and create required folders/permissions
tar -zxf $SRC/openphoto-*.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/openphoto-* $WEBROOT
rm $SRC/openphoto-*.tar.gz
chown -R root:root $WEBROOT

mkdir -p $WEBROOT/src/userdata/configs
mkdir -p $WEBROOT/src/html/photos
mkdir -p $WEBROOT/src/html/assets/cache

chown -R www-data:www-data $WEBROOT/src/userdata
chown -R www-data:www-data $WEBROOT/src/html/photos
chown -R www-data:www-data $WEBROOT/src/html/assets/cache

# configure php.ini
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 16M|" $PHPINI

# configure apache
a2dissite default
a2ensite openphoto
a2enmod rewrite
a2enmod deflate
a2enmod expires
a2enmod headers

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

