#!/bin/sh -ex

DB_NAME=openphoto
DB_USER=openphoto
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

WEBROOT=/var/www/openphoto

# create required folders and set permissions
mkdir -p $WEBROOT/src/userdata/configs
mkdir -p $WEBROOT/src/html/photos
mkdir -p $WEBROOT/src/html/assets/cache

chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/src/userdata
chown -R www-data:www-data $WEBROOT/src/html/photos
chown -R www-data:www-data $WEBROOT/src/html/assets/cache

# configure php.ini
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 16M|" $PHPINI

# configure apache
a2dissite default
a2ensite openphoto
a2enmod rewrite
a2enmod deflate
a2enmod expires
a2enmod headers

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
OP_ROOT=$(echo $WEBROOT/src/html/photos | sed "s/\//%2F/g")
URL="http://127.0.0.1/setup"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL ${URL}
$CURL ${URL} --data "email=$EMAIL&password=$ADMIN_PASS&theme=beisel2.0&appId=openphoto-frontend"

$CURL ${URL}
$CURL ${URL}/2 --data "imageLibrary=ImageMagick&database=MySql&fileSystem=Local"

$CURL ${URL}
$CURL ${URL}/3 --data "mySqlHost=localhost&mySqlUser=$DB_USER&mySqlPassword=$DB_PASS&mySqlDb=$DB_NAME&mySqlTablePrefix=&fsRoot=$OP_ROOT&fsHost=127.0.0.1%2Fphotos"

rm -f /tmp/cookie

# change site to default
CONF=$WEBROOT/src/userdata/configs/127.0.0.1.ini
sed -i "s|fsHost=.*|fsHost=${DOMAIN}/photos|" $CONF
mv $CONF $(dirname $CONF)/${DOMAIN}.ini
chmod 640 $WEBROOT/src/userdata/configs/${DOMAIN}.ini

# deny access to setup
cat >>/etc/apache2/sites-available/openphoto<<EOF
# remove to setup multiple openphoto sites
<Location /setup>
    deny from all
</Location>
EOF

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

