#!/bin/bash -e
# regenerate openphoto secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/openphoto/src/configs/defaults.ini
SALT=$(mcookie)
sed -i "s|passwordSalt=.*|passwordSalt=\"$SALT\"|" $CONF

CONF=/var/www/openphoto/src/userdata/configs/*.ini
PASSWORD=$(mcookie)
HASHPASS=$(php5 $INITHOOKS_PATH/bin/openphoto_crypt.php encrypt $PASSWORD)
sed -i "s|mySqlPassword=.*|mySqlPassword=\"$HASHPASS\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=openphoto --pass="$PASSWORD"

