#!/bin/bash -e
# set openphoto owner email, password and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/openphoto.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

